### ISSUE TITLE
SSAHA does not include fastq_split.pl

### ISSUE THREAD

**Issue by nkremerh** [cooperative-computing-lab/makeflow-examples#26]
The generated makeflow for SSAHA references a file which is not there at runtime if you follow the README instructions.

**Comment by nkremerh** [comment]
@nhazekam You may know best where this script might be.

**Comment by nhazekam** [comment]
If you look at the produce rule I think its simply a mistake in naming the rule requires fastq_split.pl and uses fastq_reduce to actually split the file. If you update this name does that address the issue?
