### ISSUE TITLE
Problem in Create_SubsetPileup.sh

### ISSUE THREAD

**Issue by balis** [cooperative-computing-lab/makeflow-examples#41]
Trying to run the Hecil workflow -- this line evaluates to -1 and sed breaks.  Setting "+1" instead seems to work in a test run.
https://github.com/cooperative-computing-lab/makeflow-examples/blob/512a3869a79a53b963cd3e2eeace7aaf87a1c9c3/hecil/Create_SubsetPileup.sh#L17

**Comment by btovar** [comment]
Bartosz, thanks for your report. It does seem that the -1 should +1. I'll submit a fix soon.
