### ISSUE TITLE
makeflow failed 

### ISSUE THREAD

**Issue by Kirito-Ma** [cooperative-computing-lab/makeflow-examples#45]
Hi, I met a problem that my makeflow did not work. I used R terminal to test it which works well. However, when I tried to use slurm makeflow to run it, it showed me the error. 

parsing /stornext/HPCScratch/home/ma.m/test.makeflow...
2022/02/09 22:12:38.02 makeflow[11201] fatal: Found end of file while completing command.
 line: 6 column: 293
Terminated

Here is the code of my makeflow:
CATEGORY=test_slurm
MEMORY=10024
CORES=4
WALL_TIME=1500
/stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Secretory_ppcseq.rds:
	Rscript /stornext/HPCScratch/home/ma.m/mengyao_data_scripts/COVID_19/run_ppcseq/run_ppcseq.R /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_de_data/Secretory_DE.rds /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Secretory_ppcseq.rds 

I thought the makeflow did not run at all. May I know how to fix it?

**Comment by btovar** [comment]
@Kirito-Ma, in makeflow spaces and new lines are important characters, I think you want:

```make
CATEGORY=test_slurm
MEMORY=10024
CORES=4
WALL_TIME=1500
/stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Secretory_ppcseq.rds:
        Rscript /stornext/HPCScratch/home/ma.m/mengyao_data_scripts/COVID_19/run_ppcseq/run_ppcseq.R /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_de_data/Secretory_DE.rds /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Secretory_ppcseq.rds

```

**Comment by btovar** [comment]
I think you were missing the tab before Rscript and the new line at the end of file.

**Comment by Itachi-505** [comment]
HI, thanks a lot. May I ask another problem? It shows similar situation. My Rscript runs well in the terminal but failed in the slurm. 
The error shows like this:

Rscript /stornext/HPCScratch/home/ma.m/mengyao_data_scripts/COVID_19/run_ppcseq/run_ppcseq.R /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_de_data/Basal_DE.rds /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Basal_ppcseq.rds failed with exit code 137
deleted makeflow.failed.1
rule 1 failed, moving any outputs to makeflow.failed.1
deleted /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Basal_ppcseq.rds

**Comment by btovar** [comment]
It should be in the same place as the `makeflow` executable. From where are you executing makeflow? The following should work:

```sh
# needed only once:
curl -O http://ccl.cse.nd.edu/software/files/cctools-7.4.3-x86_64-centos7.tar.gz
tar xf cctools-7.4.3-x86_64-centos7.tar.gz

# every time:
export PATH=$(pwd)/cctools-7.4.3-x86_64-centos7.tar.gz-dir/bin:$PATH

resource_monitor  -Omon  -- Rscript /stornext/HPCScratch/home/ma.m/mengyao_data_scripts/COVID_19/run_ppcseq/run_ppcseq.R /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_de_data/Basal_DE.rds /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Basal_ppcseq.rds
```

**Comment by Itachi-505** [comment]
Hi, I think it works this time. How to save the output into the file mon.summary?

**Comment by btovar** [comment]
Great! I think we are getting somewhere. It seems that your program uses more memory than the one you specified, and therefore is killed eventually by slurm. If you look above, you'll see:

```json
"memory":
[
17246,
"MB"
],
```

I would try by changing your makeflow memory line to:
 MEMORY=20000
and see if that works.

**Comment by Itachi-505** [comment]
Hi btovar,

Thanks a lot. It works this time!

**Comment by Itachi-505** [comment]
Hi btovar,

I have one more question. In my Rscript, I got a dataframe. I would like it to perform nothing and not save it to rds. I create an empty tibble but not save to rds. However, it always cause slurm to fail. May I ask why this is the case and how to fix it?

**Comment by btovar** [comment]
Nice, good news!

For your error, we can get the error output as follows: modify your makeflow rule to be something like:

```make
CATEGORY=test_slurm
MEMORY=20000
CORES=4
WALL_TIME=1500
/stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Secretory_ppcseq.rds ERROR-1.output:
        Rscript /stornext/HPCScratch/home/ma.m/mengyao_data_scripts/COVID_19/run_ppcseq/run_ppcseq.R /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_de_data/Secretory_DE.rds /stornext/HPCScratch/home/ma.m/single_cell_database/COVID_19/data/all_ppcseq_data/Secretory_ppcseq.rds  > ERROR-1.output 2>&1
```

That is, we add the `ERROR-1.output` file as an output, and append `> ERROR-1.output 2>&1` at the end of the command line. Once the workflow fails, you can open `ERROR-1.output` and see the exact error you are getting from R.

**Comment by Itachi-505** [comment]
Hi, thanks! I solved the problem by following your instructions.

**Comment by btovar** [comment]
Thanks for letting us know!
